import { Montserrat } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { configDotenv } from "dotenv";
import Sidebar from "./(dashboard)/components/sidebar/page";

const montserrat = Montserrat({
  display: "swap", // 'swap' ensures text is visible while the font is loading
  variable: "sans-serif",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

configDotenv();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased flex`}>
        {children}
      </body>
    </html>
  );
}
